spring:
  application:
    name: user-customer


  datasource:
    name: mysql
    url: jdbc:mysql://116.62.185.58:3306/jyxy_test?useUnicode=yes&characterEncoding=utf8&autoReconnect=true #&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: jyxy_Admin7607
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  application:
    name: user-customer
  registry:
    address: 127.0.0.1:2181,127.0.0.1:2191,127.0.0.1:2183
    protocol: zookeeper
server:
  port: 2022