CREATE TABLE u1190_kol
(
    puk VARCHAR(20) NOT NULL COMMENT '流水ID',
    user_name VARCHAR(20) COMMENT '姓名',
    sex VARCHAR(20) COMMENT '性别',
    head_pic VARCHAR(200) COMMENT '头像',
    qzone_pic VARCHAR(200) COMMENT '空间照片',
    wx_number VARCHAR(20) COMMENT '微信号',
    address VARCHAR(20) COMMENT '地址',
    age VARCHAR(24) COMMENT '年龄',
    phone_number VARCHAR(20) COMMENT '手机号',
    personal_synopsis VARCHAR(20) COMMENT '个人简介',
    sign VARCHAR(200) COMMENT '个性签名',
    hobby VARCHAR(20) COMMENT '爱好',
    affiliated_community VARCHAR(20) COMMENT '所属社区',
    grade VARCHAR(20) COMMENT '等级',
    title VARCHAR(20) COMMENT '头衔',
    post VARCHAR(20) COMMENT '职务',
    recommender VARCHAR(20) COMMENT '推荐人',
    from_type VARCHAR(20) COMMENT '来源',
    tag VARCHAR(20) COMMENT '标签',
    membership_num VARCHAR(8) COMMENT '免费会员名额',
    membership_num_used VARCHAR(8) COMMENT '已使用会员名额',
    examine_state VARCHAR(20) COMMENT '审核状态',
    meno VARCHAR(200) COMMENT '备注',
    fb1 VARCHAR(40) COMMENT '备用1',
    fb2 VARCHAR(20) COMMENT '备用2',
    fb3 VARCHAR(20) COMMENT '备用3',
    fb4 VARCHAR(200) COMMENT '备用4',
    fb5 VARCHAR(20) COMMENT '备用5',
    eb1 VARCHAR(40) COMMENT '扩展1',
    eb2 VARCHAR(80) COMMENT '扩展2',
    eb3 VARCHAR(20) COMMENT '扩展3',
    eb4 VARCHAR(10) COMMENT '扩展4',
    eb5 VARCHAR(20) COMMENT '扩展5',
    del_flag CHAR(1) DEFAULT '0' NOT NULL COMMENT '有效标识',
    create_time VARCHAR(24) DEFAULT '2017/11/12 23:00:00' NOT NULL COMMENT '创建时间',
    creator VARCHAR(20) DEFAULT 'SYSTEM' NOT NULL COMMENT '创建者',
    update_time VARCHAR(24) DEFAULT '2017/11/12 23:00:00' COMMENT '更新时间',
    updator VARCHAR(20) COMMENT '最后更新者',
PRIMARY KEY (puk)
) COMMENT '家游助力KOL'
;
