server:
  port: 2020

dubbo:
  application:
    name: user-provider
  protocol: 20880
  registry:
    address: 127.0.0.1:2181,127.0.0.1:2191,127.0.0.1:2183
    protocol: zookeeper
  scan:
    base-package: com.example.dubbo.userserviceprivoder.serviceImpl


spring:
  application:
    name: user-provider

  datasource:
    name: mysql
    url: jdbc:mysql://116.62.185.58:3306/jyxy_test?useUnicode=yes&characterEncoding=utf8&autoReconnect=true #&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: jyxy_Admin7607
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:com/example/dubbo/userserviceprivoder/bean/**/*.xml
  typeAliasesPackage: com.example.dubbo.userserviceprivoder.bean.**.*
  configuration:
    map-underscore-to-camel-case: true
